config/routes.rb
Blenderfiles::Application.routes.draw do
  devise_for :users

  resources :materials do
    member do
      post :rate
    end
  end

  match ':controller/tagged/*tags' => ':controller#tagged'

  match '/upload' => 'application#upload'

  root :to => 'materials#index'

end

app/models/material.rb
require 'tempfile'
require 'fileutils'

class Material < ActiveRecord::Base
  acts_as_taggable
  ajaxful_rateable

  validates :title, :presence => true

  has_attached_file :blend,
    :path => ":rails_root/public/system/:attachment/:id/:style/:normalized_blend_file_name",
    :url => "/system/:attachment/:id/:style/:normalized_blend_file_name" 

  Paperclip.interpolates :normalized_blend_file_name do |attachment, style|
    attachment.instance.normalized_blend_file_name
  end

  def normalized_blend_file_name
    "#{self.title.parameterize}.blend"
  end

  validates_attachment_size :blend, :less_than => 10.megabytes

  has_many :images, :as => :imageable, :dependent => :destroy

  Paperclip.interpolates :title_slug do |attachment, style|
    attachment.instance.title.parameterize
  end

  validates_uniqueness_of :blend_fingerprint, :message => "already exists in databaase"

  def self.create_from_blend(blend_path, description="", tags=[], delete_original=false)
    extract_script = Rails.root.join('lib', 'scripts', 'extract_materials.sh')

    temp = Tempfile.new('blend')
    temp_path = temp.path
    temp.close!
    FileUtils.cp blend_path, temp_path

    if delete_original
      FileUtils.rm blend_path
    end

    system("bash #{extract_script} #{temp_path}")

    materials = []
    Dir.glob("#{temp_path}-*.blend").each do |mat_blend|
      title = mat_blend.split('-')[-1].split('.')[0] # grab the *
      material = Material.create(:title => title, :description => description)
      puts "created material: #{material.title}"
      material.tag_list = tags
      material.blend = open(mat_blend)
      material.save
      if material.valid?
        material.render_images
        materials << material
      end
    end
    FileUtils.rm temp_path
    return materials
  end

  def render_images
    render_script = Rails.root.join('lib', 'scripts', 'material_preview.sh')

    puts "rendering #{self.blend.path}"
    temp = Tempfile.new('blend')
    temp_path = temp.path
    temp.close!
    FileUtils.cp self.blend.path, temp_path

    system("bash #{render_script} #{temp_path}")
    Dir.glob("#{temp_path}-*.jpg").each do |image_path|
      layer = image_path.split('-')[-1].split('.')[0] # grab the *
      image = self.images.create
      image.image = open(image_path)
      if layer == '2' # the rocket ship
        image.order = 0
      end
      image.save
    end

    FileUtils.rm temp_path
  end
  if Rails.env.production?
    handle_asynchronously :render_images
  end

  def image
    return self.images.order("`images`.`order` ASC").first.image
  end
end

app/controllers/materials_controller.rb
if Rails.env.production?
  class MaterialsSweeper < ActionController::Caching::Sweeper
    observe Material # This sweeper is going to keep an eye on the Material model

    # If our sweeper detects that a Material was created call this
    def after_create(material)
      expire_cache_for(material)
    end

    # If our sweeper detects that a Material was updated call this
    def after_update(material)
      expire_cache_for(material)
    end

    # If our sweeper detects that a Material was deleted call this
    def after_destroy(material)
      expire_cache_for(material)
    end

    private
    def expire_cache_for(material)
      expire_action(:controller => 'materials', :action => 'index')
      expire_page(:controller => 'materials', :action => 'show', :id => material.id)
    end
  end
end

class MaterialsController < ApplicationController

  if Rails.env.production?
    caches_page :show, :new
    caches_action :index, :cache_path => Proc.new { |controller| controller.params }
    cache_sweeper :materials_sweeper
  end

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.joins(:images).group("#{Material.table_name}.id").having("COUNT(#{Image.table_name}.id) > 0").order("`materials`.`blend_updated_at` DESC").paginate(:page => params[:page])

    #TODO: sort materials by number of downloads, rating, etc.

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @materials }
    end
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
    @material = Material.find(params[:id])
    #TODO: improve visual style of material.show page

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @material }
    end
  end

  # GET /materials/new
  # GET /materials/new.json
  def new
    @material = Material.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @material }
    end
  end

  # GET /materials/1/edit
  def edit
    @material = Material.find(params[:id])
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(params[:material])

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render json: @material, status: :created, location: @material }
      else
        format.html { render action: "new" }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /materials/1
  # PUT /materials/1.json
  def update
    @material = Material.find(params[:id])

    respond_to do |format|
      if @material.update_attributes(params[:material])
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  def rate
    @material = Material.find(params[:id])
    @material.rate(params[:stars], current_user, params[:dimension])
    render :update do |page|
      page.replace_html @material.wrapper_dom_id(params), ratings_for(@material, params.merge(:wrap => false))
      page.visual_effect :highlight, @car.wrapper_dom_id(params)
    end
  end

  def tagged
    @materials = Material.joins(:images).group("#{Material.table_name}.id").having("COUNT(#{Image.table_name}.id) > 0").order("`materials`.`blend_updated_at` DESC").tagged_with(params[:tags]).paginate(:page => params[:page])
    render :action => 'index'
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material = Material.find(params[:id])
    @material.destroy

    respond_to do |format|
      format.html { redirect_to materials_url }
      format.json { head :ok }
    end
  end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_form.html.erb
<%= form_for(@material) do |f| %>
  <% if @material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% @material.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :blend %><br />
    <%= f.file_field :blend %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<h1>Editing material</h1>

<%= render 'form' %>

<%= link_to 'Show', @material %> |
<%= link_to 'Back', materials_path %>

app/views/materials/index.html.erb
<% cache do %>
  <div class="content">
    <div class="page-header">
      <h1>
        <span>browsing materials</span>
        <a href="<%= url_for :controller => 'application', :action => 'upload' %>" class="pull-right btn">Upload</a>
      </h1>
    </div>
    <ul class="breadcrumb">
      <li><a href="/">Home</a> <span class="divider">/</span></li>
      <li class="active">Materials</li>
    </ul>
    <div class="row">
      <div class="span13">
        <ul class="media-grid">
          <% @materials.each do |material| %>
            <% if material.images.count > 0 %>
              <li><%= link_to image_tag(material.image.url(:thumb)), material %></li>
            <% end %>
          <% end %>
        </ul>
        <%= will_paginate @materials, :renderer => BootstrapPaginationHelper::LinkRenderer %>
      </div>
      <div class="span3">
        <h2>popular tags</h2>
        <% Material.tag_counts_on(:tags, :limit => 15, :order => "count desc").each do |tag| %>
          <a href="<%= url_for(:controller => 'materials', :action => 'tagged', :tags => [tag.name]) %>"><span class="label"><%= tag.name %></span></a>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/materials/new.html.erb
<h1>New material</h1>

<%= render 'form' %>

<%= link_to 'Back', materials_path %>

app/views/materials/show.html.erb
<style>
  .ajaxful-rating-wrapper {
    padding-top:5px;
    margin-left: 10px;
    float: left;
  }
</style>
<div class="content">
  <div class="page-header">
    <h1>
      <span style="float:left"><%= @material.title %></span>
      <%= ratings_for @material %>
      <a href="<%= @material.blend.url %>" class="pull-right btn primary">Download</a>
      <div style="clear:both;"></div>
    </h1>
  </div>
  <ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li><a href="/materials">Materials</a> <span class="divider">/</span></li>
    <li class="active"><%= @material.title %></li>
  </ul>

  <div class="row">
    <div class="span6">
      <div id="material">
        <div id="single">
          <div id="single-grid">
            <div id="single-img">
              <%= image_tag @material.image.url(:medium), :id => "material-image" %>
            </div>
          </div>
        </div>
      </div>
      <ul class="media-grid">
        <% @material.images.each do |image| %>
          <li><%= link_to_function image_tag(image.image.url(:micro)), "change_image('#material-image', '#{image.image.url(:medium)}')" %></li>
        <% end %>
      </ul>
    </div>
    <div class="span4">
    </div>
    <div class="span4">
      <h3>created on:</h3>
      <%= time_tag @material.created_at %>
      <h3>tags:</h3>
      <% @material.tag_list.each do |tag| %>
        <span class="label"><%= tag %></span>
      <% end %>
    </div>
  </div>
</div>